import { Ratio } from '@/enum/ratio'
export const analysisConfig = {
  mechanical: {
    left: [
      {
        label: 'closingOperationsNum',
        title: '合闸操作次数',
        value: '',
        unit: '次',
        multiply: Ratio.One,
      },
      {
        label: 'openingOperationsNum',
        title: '分闸操作次数',
        value: '',
        unit: '次',
        multiply: Ratio.One,
      },
      {
        label: 'energyStorageTime',
        title: '储能时间',
        value: '',
        unit: 's',
        multiply: Ratio.ZeroAndZeroOne,
      },
      {
        label: 'energyStorageMotorMaxElectric',
        title: '储能电机最大电流',
        value: '',
        unit: 'A',
        multiply: Ratio.ZeroAndOne,
      },
      {
        label: 'chassisVehicleNum',
        title: '底盘车操作次数',
        value: '',
        unit: '次',
        multiply: Ratio.One,
      },
      {
        label: 'chassisVehicleActionTime',
        title: '底盘车动作时间',
        value: '',
        unit: 's',
        multiply: Ratio.One,
      },
      {
        label: 'chassisVehicleMotorMaxElectric',
        title: '底盘车电机最大电流',
        value: '',
        unit: 'A',
        multiply: Ratio.ZeroAndOne,
      },
      {
        label: 'groundingSwitchNum',
        title: '接地开关操作次数',
        value: '',
        unit: '次',
        multiply: Ratio.One,
      },
      {
        label: 'groundingSwitchActionTime',
        title: '接地开关动作时间',
        value: '',
        unit: 's',
        multiply: Ratio.One,
      },
      {
        label: 'groundingSwitchMotorMaxElectric',
        title: '接地开关电机最大电流',
        value: '',
        unit: 'A',
        multiply: Ratio.ZeroAndOne,
      },
    ],
    right: [
      { label: 'speed', title: '速度', value: 0, unit: 'm/s', state: 0 },
      { label: 'time', title: '时间', value: 0, unit: 'ms', state: 0 },
      { label: 'distance', title: '总行程', value: 0, unit: 'mm', state: 0 },
      { label: 'contactDistance', title: '开距', value: 0, unit: 'mm', state: 0 },
      { label: 'overContactDistance', title: '超程', value: 0, unit: 'mm', state: 0 },
      { label: 'maxCoil', title: '线圈峰值电流', value: 0, unit: 'A', state: 0 },
    ],
  },
  temperature: {
    left: [
      {
        label: 'breakerUpperATemperature',
        title: '断路器上触臂温升A',
        value: '',
        unit: '℃',
        multiply: Ratio.ZeroPointOne,
      },
      {
        label: 'breakerUpperBTemperature',
        title: '断路器上触臂温升B',
        value: '',
        unit: '℃',
        multiply: Ratio.ZeroPointOne,
      },
      {
        label: 'breakerUpperCTemperature',
        title: '断路器上触臂温升C',
        value: '',
        unit: '℃',
        multiply: Ratio.ZeroPointOne,
      },
      {
        label: 'breakerLowerATemperature',
        title: '断路器下触臂温升A',
        value: '',
        unit: '℃',
        multiply: Ratio.ZeroPointOne,
      },
      {
        label: 'breakerLowerBTemperature',
        title: '断路器下触臂温升B',
        value: '',
        unit: '℃',
        multiply: Ratio.ZeroPointOne,
      },
      {
        label: 'breakerLowerCTemperature',
        title: '断路器下触臂温升C',
        value: '',
        unit: '℃',
        multiply: Ratio.ZeroPointOne,
      },
      {
        label: 'breakerTemperature',
        title: '断路器室温度',
        value: '',
        unit: '℃',
        multiply: Ratio.ZeroAndOne,
      },
      {
        label: 'breakerHumidity',
        title: '断路器室湿度',
        value: '',
        unit: '%',
        multiply: Ratio.ZeroPointOne,
      },
    ],
    right: [
      {
        label: 'mainBusbarATemperature',
        title: '主母排温升A',
        value: '',
        unit: '℃',
        multiply: Ratio.ZeroPointOne,
      },
      {
        label: 'mainBusbarBTemperature',
        title: '主母排温升B',
        value: '',
        unit: '℃',
        multiply: Ratio.ZeroPointOne,
      },
      {
        label: 'mainBusbarCTemperature',
        title: '主母排温升C',
        value: '',
        unit: '℃',
        multiply: Ratio.ZeroPointOne,
      },
      {
        label: 'outletCableATemperature',
        title: '出线电缆温升A',
        value: '',
        unit: '℃',
        multiply: Ratio.ZeroPointOne,
      },
      {
        label: 'outletCableBTemperature',
        title: '出线电缆温升B',
        value: '',
        unit: '℃',
        multiply: Ratio.ZeroPointOne,
      },
      {
        label: 'outletCableCTemperature',
        title: '出线电缆温升C',
        value: '',
        unit: '℃',
        multiply: Ratio.ZeroPointOne,
      },
      {
        label: 'cableTemperature',
        title: '电缆室温度',
        value: '',
        unit: '℃',
        multiply: Ratio.ZeroAndOne,
      },
      {
        label: 'cableHumidity',
        title: '电缆室湿度',
        value: '',
        unit: '%',
        multiply: Ratio.ZeroPointOne,
      },
    ],
  },
}
